server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:8181/eureka/

zuul:
   routes:
      api-login:
         path: /provider
         serviceId: provider-service

spring:
    application:
        name: api-gateway

#日志
logging:
  config: F:/github/SpringCloud/api-gateway/src/main/resources/logback.xml

