eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://192.168.1.101:8181/eureka/
    instance:
        hostname: node1
server:
    port: 8181
logging:
    config:  F:/github/SpringCloud/eureka-server/src/main/resources/logback.xml

